import { Container } from '@chakra-ui/react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header/Header';
import Infor from '../components/Infor';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Profile of N3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo1.png" />
      </Head>

      <header className={styles.header}>
        <Header />
      </header>
      <main className={styles.main}>
        <Container maxW="container.sm">
          <Infor />
        </Container>
      </main>

      <footer className={styles.footer}>
        <span>© 2022 N3 All Rights Reserved.</span>
      </footer>
    </div>
  );
};

export default Home;
